# Default docker compose for postgres; will need changing

# Use postgres/example user/password credentials
version: '3.5'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes: 
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - target: 5432
        published: 25432
        protocol: tcp
        mode: host

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080